Splits Execute Method into 'plan' and 'execute' methods
shaun-edwards/moveit_simple pull request #17
Opened 2017-05-30 22:40 UTC by geoffreychiou

@shaun-edwards Is this what you were thinking?

2017-06-01 04:16 UTC, shaun-edwards requested changes

2017-06-01 04:16 UTC, shaun-edwards commented on moveit_simple/include/moveit_simple/moveit_simple.h
> -  bool execute(const std::string traj_name);
Normally I would have left the original method in (with a deprecated notice).  That way you don't break others code.  Don't worry about it for now.

2017-06-01 04:16 UTC, shaun-edwards commented on moveit_simple/src/moveit_simple.cpp
> +bool Robot::execute(const std::string traj_name,
Why is the `traj_name` argument required in this method?  It looks like it is only used for logging, whereas in the previous implementation it was required to look-up the trajectory.

2017-06-01 04:16 UTC, shaun-edwards commented on moveit_simple/include/moveit_simple/moveit_simple.h
> -  bool execute(const std::string traj_name);
Actually, after seeing your tests, I like usability of this method.  The "new" methods give you granular control for testing and other uses, but we still need this method for simplicity.

2017-06-01 04:16 UTC, shaun-edwards commented on moveit_simple/test/moveit_simple.cpp
> +  EXPECT_TRUE(robot.plan(TRAJECTORY_NAME, trajectory_goal));
This test shows how we've made things harder to use...see comments above.

2017-06-01 04:16 UTC, shaun-edwards commented on moveit_simple/test/moveit_simple.cpp
> +  EXPECT_FALSE(robot.execute("Random Name", empty_goal));
How does this work...where does execute verify that the trajectory name is correct?

2017-06-01 04:16 UTC, shaun-edwards commented on moveit_simple/test/moveit_simple.cpp
> +  EXPECT_FALSE(robot.execute(TRAJECTORY_NAME, empty_goal));
Good check!

2017-06-05 16:46 UTC, geoffreychiou commented on moveit_simple/test/moveit_simple.cpp
> +  EXPECT_FALSE(robot.execute("Random Name", empty_goal));
Good point, this is a bad check, I'll remove it. It was only passing because the test because it failed due to an empty goal.

2017-06-05 16:47 UTC, geoffreychiou commented on moveit_simple/src/moveit_simple.cpp
> +bool Robot::execute(const std::string traj_name,
Should we not pass it in even if it is only used for logging?

2017-06-05 21:10 UTC, geoffreychiou commented on moveit_simple/test/moveit_simple.cpp
> +  EXPECT_TRUE(robot.plan(TRAJECTORY_NAME, trajectory_goal));
Would something like this be easier?
``` C++
struct TrajectoryDefinition
{
  TrajectoryDefinition(const std::string &input_name) : name(input_name)
  moveit_simple::TrajectoryGoal goal;
  const std::string name;
};

moveit_simple::TrajectoryDefinition trajectory("traj1");
robot.plan(trajectory);
robot.execute(trajectory);
```

2017-06-06 04:20 UTC, shaun-edwards commented on moveit_simple/src/moveit_simple.cpp
> +bool Robot::execute(const std::string traj_name,
This relies on the user of you class/method to do the right thing.  The argument also impies it's used in some meaningful way, but that's not true.

2017-06-06 04:22 UTC, shaun-edwards commented on moveit_simple/test/moveit_simple.cpp
> +  EXPECT_TRUE(robot.plan(TRAJECTORY_NAME, trajectory_goal));
I'm not sure how defining a new structure makes it easier.  My main concern was getting rid of a method that planned and executed a trajectory in one shot.

2017-07-05 17:05 UTC, shaun-edwards commented
@geoffreychiou, don't forget about this one.

2017-08-09 19:16 UTC, nsnitish commented on moveit_simple/test/moveit_simple.cpp
> +  EXPECT_TRUE(robot.plan(TRAJECTORY_NAME, trajectory_goal));
@shaun-edwards ! Won't it be easier for user to execute the trajectory by just passing the traj_name? trajectory_goal can be passed internally by using a simple map

 < std::map<std::string, TrajectoryInfo> traj_info_map_>

2017-08-09 19:31 UTC, shaun-edwards commented on moveit_simple/test/moveit_simple.cpp
> +  EXPECT_TRUE(robot.plan(TRAJECTORY_NAME, trajectory_goal));
Or we could support both and/or all combinations of plan/execute.

2017-08-09 19:39 UTC, nsnitish commented on moveit_simple/test/moveit_simple.cpp
> +  EXPECT_TRUE(robot.plan(TRAJECTORY_NAME, trajectory_goal));
Is it like
1. planAndExecute(traj_name)
2. plan(traj_name, trajectory_goal) and execute(trajectory_goal)?

2017-11-07 20:29 UTC, closed without merging