Moveit simple ikfast collision check wrapper
shaun-edwards/moveit_simple pull request #38
Opened 2017-11-27 17:12 UTC by MauleshSTrivedi

First commit. I will be adding the updated URDFs with the unit tests for custom_tool collision check.

2017-11-27 17:28 UTC, shaun-edwards requested changes

2017-11-27 17:28 UTC, shaun-edwards commented on moveit_simple/cfg/moveit_simple_dynamic_reconfigure_.params
> +gen.add("speed_modifier", paramtype="double", description="Speed Modifier for Execution", min=0.01, max=1.0, default=0.25, configurable=True)
Set back to 1.0

2017-11-27 17:28 UTC, shaun-edwards commented on moveit_simple/src/moveit_simple.cpp
> +  ROS_INFO_STREAM("Loading MoveIt objects based on, robot description: " << robot_description
Create an init function.

2017-11-27 17:28 UTC, shaun-edwards commented on moveit_simple/src/moveit_simple.cpp
> +  kinematics_base_link_override = kinematics_base_link;
Instead cache these values as either overrides or the `joint_group_->getSolverInstance()->getTipFrame();`, etc...

2017-11-30 16:51 UTC, MauleshSTrivedi commented
@shaun-edwards Modified according to request. Please review. Thanks. :)

2018-03-13 14:14 UTC, closed without merging

2018-03-13 14:14 UTC, MauleshSTrivedi commented
Moving this to #47